all:
  hosts:
    k3sCluster:
  children: 
    conductor:
      hosts:
        10.0.0.246: # banana pi
    nodes:
      hosts:
        10.0.0.247: # raspi 3
        10.0.0.248: # raspi 2
  vars:
    ansible_connection: ssh
    ansible_python_interpreter: '/usr/bin/env python3'
    ansible_become_method: sudo
    ansible_become: yes
    ansible_become_password_file: '/home/caboose/codingProjects/kubernetes/k3s/.config/password.yaml'
